# -*- coding: utf-8 -*-
"""Assignment 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZnEE52Xy2wqcUgvfHeJZTqEIYQKNRssU

# Load library
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

"""# Import Datset (Bank Marketing Dataset)"""

pip install ucimlrepo

from ucimlrepo import fetch_ucirepo

# fetch dataset
bank_marketing = fetch_ucirepo(id=222)

# data (as pandas dataframes)
X = bank_marketing.data.features
y = bank_marketing.data.targets

# metadata
print(bank_marketing.metadata)

# variable information
print(bank_marketing.variables)

"""# 1. Data Preparation

## Encode y before spliting (Yes/No -> 1/0)
"""

y = y['y'].map({'no': 0, 'yes': 1})

"""## Train / Val / Test Split (70/15/15)"""

from sklearn.model_selection import train_test_split

# split first
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42) # 70% Training

X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42) # 15% Validation + 15% Testing

"""## Handle Missing value"""

print(X_train.isnull().sum().sort_values(ascending=False).head())

cat_cols = X.select_dtypes(include='object').columns
num_cols = X.select_dtypes(exclude='object').columns

missing_pct = X.isnull().mean() * 100
missing_pct = missing_pct.sort_values(ascending=False)

print(missing_pct) # poutcome has 81.7% of missing value and contact has 28.8% of missing value

"""## Data Preprocessing"""

preprocessor = ColumnTransformer([
    # numeric features
    ('num', Pipeline([
        ('imputer', SimpleImputer(strategy='median')), # Impute the missing value as median
        ('scaler', StandardScaler())   # standarization, needed for MLP
    ]), num_cols),

    # categorical features
    ('cat', Pipeline([
        ('imputer', SimpleImputer(strategy='constant', fill_value='missing')), # Fill missing value (NA) as missing
        ('onehot', OneHotEncoder(handle_unknown='ignore')) # label encoding -> transform categorical to [0 1]
    ]), cat_cols)
])

"""# Gradient Boosted Tree (GBDT)"""

from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from xgboost import plot_importance
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, average_precision_score
from sklearn.metrics import precision_recall_curve

### Baseline
xgb_model = XGBClassifier(
    # learning_rate=0.1, # small learning_rate usually needs more trees
    # n_estimators=200, # 200 trees
    # max_depth=5, # maximum depth of each individual tree (5 as max depth)
    # subsample=0.8, # Each tree is trained on 80% of the training rows
    # reg_alpha=0, # L1 regularization on the leaf weights (0 = no L1 penalty, larger = more penalty)
    # reg_lambda=1, # L2 regularization on the leaf weights (1 = standard and some regularization, larger = more regularation)
    random_state=42 # Randome.seed, help to Replicate result, reproducibility
)

xgb_pipeline = Pipeline([
    ('prep', preprocessor), # Data preprocessor from our data preparation step
    ('model', xgb_model) # Model is xgboost
])

# Hypertuning
param_grid = {

    # smoother learning
    'model__learning_rate': [0.01, 0.05, 0.1, 0.3],

    # control complexity
    'model__max_depth': [3, 4, 5],

    # more trees for smaller LR
    'model__n_estimators': [300, 500, 800],

    # subsampling (already good)
    'model__subsample': [0.7, 0.8],
    'model__colsample_bytree': [0.7, 0.8],

    # regularization (IMPORTANT)
    'model__reg_lambda': [1, 5, 10],
    'model__gamma': [0, 1, 3],
    'model__min_child_weight': [1, 3, 5],

    # imbalance handling (CRITICAL)
    'model__scale_pos_weight': [1, 3, 5, 10]
}

import time
# xgb model using RandomizedSearchCV
grid_xgb = RandomizedSearchCV(
    estimator=xgb_pipeline,
    param_distributions=param_grid,
    n_iter=50,              # only try 50 combos
    scoring='f1',
    cv=3,
    n_jobs=-1,
    verbose=1,
    random_state=42
)

xgb_start = time.time()

# fit ONLY on training data (no leakage)
grid_xgb.fit(X_train, y_train)

xgb_end = time.time()

# Learning rate analysis
results = grid_xgb.cv_results_
df = pd.DataFrame(results)

df_lr_mean = df.groupby('param_model__learning_rate')['mean_test_score'].mean()
df_lr_std  = df.groupby('param_model__learning_rate')['mean_test_score'].std()

plt.figure()

plt.errorbar(
    df_lr_mean.index,
    df_lr_mean.values,
    yerr=df_lr_std.values,
    marker='o'
)

# best learning rate
best_lr = df_lr_mean.idxmax()
best_score = df_lr_mean.max()

plt.axvline(x=best_lr, linestyle='--')
plt.annotate(f'Best LR ≈ {best_lr}',
             xy=(best_lr, best_score),
             xytext=(best_lr + 0.05, best_score + 0.005),
             arrowprops=dict(arrowstyle='->'))

plt.grid(True, linestyle='--', alpha=0.5)

plt.title("Learning Rate vs F1 Score (with variability)")
plt.xlabel("Learning Rate")
plt.ylabel("Mean CV F1 Score")

plt.show()

# best hyperparameters found during search
print("Best params:", grid_xgb.best_params_)

# best cross-validation score
print("Best CV score:", grid_xgb.best_score_)

# Get best params from GridSearch
best_params = grid_xgb.best_params_

# Rebuild best XGB model
best_xgb = XGBClassifier(
    learning_rate=best_params['model__learning_rate'],
    max_depth=best_params['model__max_depth'],
    n_estimators=best_params['model__n_estimators'],
    subsample=best_params['model__subsample'],
    colsample_bytree=best_params['model__colsample_bytree'],
    reg_lambda=best_params['model__reg_lambda'],
    random_state=42,
    eval_metric='logloss',
    early_stopping_rounds=20
)

# Rebuild pipeline
best_pipeline = Pipeline([
    ('prep', preprocessor),
    ('model', best_xgb)
])

# Fit preprocessor
X_train_t = preprocessor.fit_transform(X_train)
X_val_t   = preprocessor.transform(X_val)

# Fit model with early stopping

best_xgb.fit(
    X_train_t, y_train,
    eval_set=[(X_val_t, y_val)],
    verbose=False
)

# Get feature names after fitting preprocessor
feature_names = preprocessor.get_feature_names_out()

# Get importances from trained model
importances = best_xgb.feature_importances_

# Build dataframe
feat_df = pd.DataFrame({
    "feature": feature_names,
    "importance": importances
}).sort_values(by="importance", ascending=False)

# Clean names
feat_df["feature"] = feat_df["feature"].str.replace(r"^(num__|cat__)", "", regex=True)

feat_df.head(10)

# Plot the result
plt.figure(figsize=(12, 10))

plt.barh(
    feat_df["feature"].head(20)[::-1],   # top 20 features
    feat_df["importance"].head(20)[::-1]
)

plt.title("Top 20 Feature Importances (Best XGBoost Model)")
plt.xlabel("Importance")
plt.ylabel("Feature")

plt.show()

"""# Train xgboost on val set"""

# preprocessor
preprocessor = best_pipeline.named_steps["prep"]

# Transform data
X_train_trans = preprocessor.transform(X_train)
X_val_trans = preprocessor.transform(X_val)

# fit xgb
xgb_model = best_pipeline.named_steps["model"]

xgb_model.fit(
    X_train_trans, y_train,
    eval_set=[(X_train_trans, y_train), (X_val_trans, y_val)],
    verbose=False
)

results = xgb_model.evals_result()

train_loss = results['validation_0']['logloss']
val_loss = results['validation_1']['logloss']

plt.figure()
plt.plot(train_loss, label="Training Loss")
plt.plot(val_loss, label="Validation Loss")

plt.xlabel("Number of Trees")
plt.ylabel("Log Loss")
plt.title("XGBoost Training vs Validation Loss")
plt.legend()

plt.tight_layout()
plt.savefig("xgb_loss.png")
plt.show()



"""# 3. Multi-Layer Perception (MLP)"""

from sklearn.neural_network import MLPClassifier

# Define MLP model
mlp_model = MLPClassifier(
    # hidden_layer_sizes=(128, 64), # 2 hidden layers: 1 = 128 neurons, 2 = 64 neurons
    # learning_rate_init=0.001, # Initial learning rate: How big each weight update
    max_iter=200, # Max iteration of the model
    # Following parameters are to avoid the overfitting
    alpha=0.01,                  #  L2 regularization
    early_stopping=True,          # stops training when validation stops improving
    validation_fraction=0.1,      # 10% of training used as validation
    random_state=42 # Random.seed, Reproducibility
)

# Build Pipeline (Data processing and model)
mlp_pipeline = Pipeline([
    ('prep', preprocessor),
    ('model', mlp_model)
])

# define parameter grid
param_grid_mlp = {
    'model__hidden_layer_sizes': [
        (32,),
        (64,),
        (128, 64)
    ],

    'model__learning_rate_init': [
        0.001,
        0.01
    ],

    'model__alpha': [
        0.0001,
        0.001,
        0.01,
        0.1
    ]
}

# Fit the mlp pipeline in to training set of X and y
mlp_pipeline.fit(X_train, y_train)

# GridSearchCV for hyperparameter tunning
grid_mlp = GridSearchCV(
    estimator=mlp_pipeline,
    param_grid=param_grid_mlp,
    scoring='f1',
    cv=3,
    n_jobs=-1,
    verbose=1
)
mlp_start = time.time()
grid_mlp.fit(X_train, y_train)
mlp_end = time.time()

# Best model
print("Best params:", grid_mlp.best_params_)
print("Best CV score:", grid_mlp.best_score_)

best_mlp = grid_mlp.best_estimator_ # Simpler model wins: 64 neurons

# Evaluate on validation set
y_val_pred = best_mlp.predict(X_val)
y_val_prob = best_mlp.predict_proba(X_val)[:, 1]



mlp_val_results = {
    "Accuracy": accuracy_score(y_val, y_val_pred),
    "Precision": precision_score(y_val, y_val_pred),
    "Recall": recall_score(y_val, y_val_pred),
    "F1": f1_score(y_val, y_val_pred),
    "AUC-PR": average_precision_score(y_val, y_val_prob)
}

mlp_val_results

# Plot the loss curve
plt.plot(best_mlp.named_steps['model'].loss_curve_)
plt.title("MLP Training Loss (Best Model)")
plt.xlabel("Iterations")
plt.ylabel("Loss")
plt.show()

cv_results = pd.DataFrame(grid_mlp.cv_results_)

# extract architecture + score
arch_results = cv_results[[
    "param_model__hidden_layer_sizes",
    "mean_test_score"
]].copy()

arch_results.columns = ["Architecture", "Validation F1"]

# sort for nicer display
arch_results = arch_results.sort_values(by="Validation F1", ascending=False)

print(arch_results)

arch_plot = arch_results.groupby("Architecture")["Validation F1"].mean().reset_index()

plt.figure()
plt.plot(
    arch_plot["Architecture"].astype(str),
    arch_plot["Validation F1"],
    marker='o'
)

plt.xlabel("Hidden Layer Architecture")
plt.ylabel("Mean Validation F1-score")
plt.title("MLP Architecture vs Validation Performance")
plt.xticks(rotation=30)
plt.tight_layout()
plt.savefig("mlp_arch.png")
plt.show()

"""# 4. Evaluation (Accuracy, Precision, Recall, F1)"""

def evaluate(model, X, y):
    y_pred = model.predict(X)
    y_prob = model.predict_proba(X)[:,1]

    return {
        "Accuracy": accuracy_score(y, y_pred),
        "Precision": precision_score(y, y_pred),
        "Recall": recall_score(y, y_pred),
        "F1": f1_score(y, y_pred),
        "AUC-PR": average_precision_score(y, y_prob)
    }

best_xgb = grid_xgb.best_estimator_
best_mlp = grid_mlp.best_estimator_

xgb_results = evaluate(best_xgb, X_test, y_test)
mlp_results = evaluate(best_mlp, X_test, y_test)

print("Tuned XGB:", xgb_results)
print("Tuned MLP:", mlp_results)

results_df = pd.DataFrame([
    xgb_results,
    mlp_results
], index=["XGBoost", "MLP"])

results_df.round(3)

"""The tuned XGBoost model achieves higher recall (0.771), F1 score (0.652), and AUC-PR (0.641), making it better at identifying positive cases in an imbalanced setting. In contrast, the MLP model attains slightly higher accuracy (0.912) and precision (0.631), but lower recall (0.557) and overall F1 performance. Overall, XGBoost provides a better balance between precision and recall, while MLP is more conservative but less effective at capturing positives."""

# XGBoost
y_prob_xgb = best_xgb.predict_proba(X_test)[:, 1]
precision_xgb, recall_xgb, _ = precision_recall_curve(y_test, y_prob_xgb)

# MLP
y_prob_mlp = best_mlp.predict_proba(X_test)[:, 1]
precision_mlp, recall_mlp, _ = precision_recall_curve(y_test, y_prob_mlp)

# Plot
plt.figure(figsize=(8, 6))

plt.plot(recall_xgb, precision_xgb, label="XGBoost")
plt.plot(recall_mlp, precision_mlp, label="MLP")

plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve")
plt.legend()

plt.show()

"""## Check if models (xgb, mlp) are overfiiting"""

train_results = evaluate(best_xgb, X_train, y_train)
val_results = evaluate(best_xgb, X_val, y_val)

print("Train:", train_results)
print("Validation:", val_results)

train_results = evaluate(best_mlp, X_train, y_train)
val_results = evaluate(best_mlp, X_val, y_val)

print("Train:", train_results)
print("Validation:", val_results)

"""The performance difference between training and validation is relatively small, which suggests only mild overfitting rather than severe overfitting. The reduction in overfitting is not because RandomizedSearchCV itself fixes overfitting, but because it helped identify a better combination of hyperparameters more efficiently than GridSearchCV.

# Evaluation Metric with training time
"""

# Time difference
xgb_time = xgb_end - xgb_start
print(f"XGBoost training time: {xgb_time:.2f} seconds")

mlp_time = mlp_end - mlp_start
print(f"MLP training time: {mlp_time:.2f} seconds")

# create results df
results_df = pd.DataFrame([
    xgb_results,
    mlp_results
], index=["XGBoost", "MLP"])

# add training time column
results_df["Training Time (sec)"] = [xgb_time, mlp_time]

# round for display
results_df = results_df.round(3)

print(results_df)



